In [1]:
#Imports
from openparticle import Fock, ParticleOperator
from openparticle.qubit_mappings import *

In [2]:
#An example state

f_occ = [] # no fermion
af_occ = [] # no antifermion

# the second argument in the b_occ tuple is n, and the first argument is the mode which will always be 0
n = 5
b_occ = [(0, n)] # One boson in state 5

x = Fock(f_occ = f_occ, af_occ = af_occ, b_occ = b_occ)
print(x)

1.0 * |; ; (0, 5)⟩


In [3]:
from openparticle import FermionOperator, AntifermionOperator, BosonOperator

In [4]:
op = ParticleOperator('a0 a0 a0 a0')
print(op)

1.0*a_0a_0a_0a_0


In [5]:
# apply the operators on the state
print(op * x)

# aaaa
# check if the coeff matches our work
np.sqrt((n - 1) * (n - 2) * (n - 3) * n)


10.954451150103324 * |; ; (0, 1)⟩


10.954451150103322

In [6]:
op = ParticleOperator('a0 a0 a0 a0^')
print(op * x)

# aaaa^
# check if the coeff matches our work
np.sqrt((n - 1) * (n + 1) * (n + 1) * n)

26.832815729997474 * |; ; (0, 3)⟩


26.832815729997478

In [7]:
op = ParticleOperator('a0 a0 a0^ a0')
print(op * x)

# aaaa^
# check if the coeff matches our work
np.sqrt((n - 1) * n * n * n)

22.3606797749979 * |; ; (0, 3)⟩


22.360679774997898

In [8]:
op = ParticleOperator('a0 a0 a0^ a0^')
print(op * x)

# aaa^a^
# check if the coeff matches our work
np.sqrt((n + 1) * (n + 1) * (n + 2) * (n + 2))

42.0 * |; ; (0, 5)⟩


42.0

In [9]:
op = ParticleOperator('a0 a0^ a0 a0')
print(op * x)

# aa^aa
# check if the coeff matches our work
np.sqrt((n - 1) * (n - 1) * (n - 1) * n)

17.88854381999832 * |; ; (0, 3)⟩


17.88854381999832

In [10]:
op = ParticleOperator('a0 a0^ a0 a0^')
print(op * x)

# aa^aa^
# check if the coeff matches our work
np.sqrt((n + 1) * (n + 1) * (n + 1) * (n + 1))

35.999999999999986 * |; ; (0, 5)⟩


36.0

In [11]:
op = ParticleOperator('a0 a0^ a0^ a0')
print(op * x)

# aa^a^a
# check if the coeff matches our work
np.sqrt((n + 1) * (n + 1) * n * n)

30.0 * |; ; (0, 5)⟩


30.0

In [12]:
op = ParticleOperator('a0 a0^ a0^ a0')
print(op * x)

# aa^a^a
# check if the coeff matches our work
np.sqrt((n + 1) * (n + 1) * n * n)

30.0 * |; ; (0, 5)⟩


30.0

In [13]:
op = ParticleOperator('a0 a0^ a0^ a0^')
print(op * x)

# aa^a^a^
# check if the coeff matches our work
np.sqrt((n + 3) * (n + 3) * (n + 1) * (n + 2))

51.84592558726289 * |; ; (0, 7)⟩


51.84592558726288

In [14]:
op = ParticleOperator('a0^ a0 a0 a0')
print(op * x)

# a^aaa
# check if the coeff matches our work
np.sqrt((n - 2) * n * (n - 1) * (n - 2))

13.416407864998737 * |; ; (0, 3)⟩


13.416407864998739

In [15]:
op = ParticleOperator('a0^ a0 a0 a0^')
print(op * x)

# a^aaa^
# check if the coeff matches our work
np.sqrt(n * n * (n + 1) * (n + 1))

30.0 * |; ; (0, 5)⟩


30.0

In [16]:
op = ParticleOperator('a0^ a0 a0^ a0')
print(op * x)

# a^aa^a
# check if the coeff matches our work
np.sqrt(n * n * n * n)

25.000000000000007 * |; ; (0, 5)⟩


25.0

In [17]:
op = ParticleOperator('a0^ a0 a0^ a0^')
print(op * x)

# a^aa^a^
# check if the coeff matches our work
np.sqrt((n + 2) * (n + 2) * (n + 2) * (n + 1))

45.365184888855026 * |; ; (0, 7)⟩


45.36518488885502

In [18]:
op = ParticleOperator('a0^ a0^ a0 a0')
print(op * x)

# a^a^aa
# check if the coeff matches our work
np.sqrt((n - 1) * (n - 1) * n * n)

20.000000000000004 * |; ; (0, 5)⟩


20.0

In [19]:
op = ParticleOperator('a0^ a0^ a0 a0^')
print(op * x)

# a^a^aa^
# check if the coeff matches our work
np.sqrt((n + 1) * (n + 1) * (n + 2) * (n + 1))

38.884444190447155 * |; ; (0, 7)⟩


38.88444419044716

In [20]:
op = ParticleOperator('a0^ a0^ a0^ a0')
print(op * x)

# a^a^a^a
# check if the coeff matches our work
np.sqrt((n + 1) * n * (n + 2) * n)

32.403703492039305 * |; ; (0, 7)⟩


32.4037034920393

In [21]:
op = ParticleOperator('a0^ a0^ a0^ a0^')
print(op * x)

# a^a^a^a^
# check if the coeff matches our work
np.sqrt((n + 1) * (n + 3) * (n + 2) * (n + 4))

54.99090833947009 * |; ; (0, 9)⟩


54.99090833947008

In [22]:
# # initialize a 2d matrix/array
# rows, cols = (10, 10)
# arr = [[0] * cols for _ in range(rows)]
# print(np.matrix(arr))

# # m is a row matrix and n is a col matrix
# m = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# n = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# def checkDiagonal(m, n, val):
#     return m - (n + val) == 0

# def calcCoeff(n):
#     return np.sqrt((n - 3) * (n - 2) * (n - 1) * n)

# # aaaa
# val = -4

# def displayMatrix(m, n, val):
#     for row in m:
#         for col in n:
#             if checkDiagonal(row, col, val):
#                 arr[row - 1][col - 1] = calcCoeff(col)
#     return arr

# print(np.matrix(displayMatrix(m, n, val)))


In [23]:
from openparticle import ConjugateFock

def updateN(n):
    # state N ket
    f_occ = [] # no fermion
    af_occ = [] # no antifermion

    # the second argument in the b_occ tuple is n, and the first argument is the mode which will always be 0
    b_occ = [(0, n)] # One boson in mode 0

    N = Fock(f_occ = f_occ, af_occ = af_occ, b_occ = b_occ)
    # print(N)

    return N

def updateM_bra(m):
    # state M ket
    f_occ = [] # no fermion
    af_occ = [] # no antifermion

    # the second argument in the b_occ tuple is n, and the first argument is the mode which will always be 0
    b_occ = [(0, m)] # One boson in mode 0

    M = Fock(f_occ = f_occ, af_occ = af_occ, b_occ = b_occ)
    M_bra = ConjugateFock.from_state(M)

    # print(M_bra)
    return M_bra

In [24]:
def checkDiagonal(m, n, val):
    return m - (n + val) == 0

def calcCoeff(n, a, b, c, d):
    return np.sqrt((n + a) * (n + b) * (n + c) * (n + d))

# H7

def displayMatrixOld(arr, val, a, b, c, d):
    for m in range(1, 11):
        for n in range(1, 11):
            if checkDiagonal(m, n, val):
                arr[m - 1][n - 1] = calcCoeff(n, a, b, c, d)
    return arr

In [25]:
# define operator
H1 = ParticleOperator('a0 a0 a0 a0')


In [26]:
def initializeMatrix():
    # initialize a 2d matrix/array
    rows, cols = (10, 10)
    arr = [[0] * cols for _ in range(rows)]
    # print(np.matrix(arr))
    return arr


def displayMatrix(arr, H):
    for m in range(1, 11):
        for n in range(1, 11):
                # print("(", m, ", ", n, ")")
                arr[m - 1][n - 1] = updateM_bra(m) * H * updateN(n)
    return arr

print(np.matrix(displayMatrix(initializeMatrix(), H1)))
print(np.matrix(displayMatrixOld(initializeMatrix(), -4, -3, -2, -1, 0)))

[[ 0.          0.          0.          0.         10.95445115  0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.         18.97366596
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
  28.98275349  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.         40.98780306  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.         54.99090834  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.         70.9929574 ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.   

NOTE: adding multiple operators is not implemented yet!

In [27]:
H2 = ParticleOperator('a0 a0 a0 a0^')
print(np.matrix(displayMatrix(initializeMatrix(), H2)))
print(np.matrix(displayMatrixOld(initializeMatrix(), -2, -1, 0, 1, 1)))

[[  0.           0.           9.79795897   0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.          17.32050808   0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.          26.83281573
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
   38.34057903   0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.          51.84592559   0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.          67.34983296   0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.          84.85281374   0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0

In [28]:
H3 = ParticleOperator('a0 a0 a0^ a0')
print(np.matrix(displayMatrix(initializeMatrix(), H3)))
print(np.matrix(displayMatrixOld(initializeMatrix(), -2, -1, 0, 0, 0)))

[[ 0.          0.          7.34846923  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.         13.85640646  0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         22.36067977  0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.         32.86335345
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
  45.36518489  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.         59.86651819  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.         76.36753237  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.         94.86832981]
 [ 0.          0.          0.          0.          0.   

In [29]:
H4 = ParticleOperator('a0 a0 a0^ a0^')
print(np.matrix(displayMatrix(initializeMatrix(), H4)))
print(np.matrix(displayMatrixOld(initializeMatrix(), 0, 1, 1, 2, 2)))
np.allclose(np.matrix(displayMatrix(initializeMatrix(), H4)), np.matrix(displayMatrixOld(initializeMatrix(), 0, 1, 1, 2, 2)))

[[  6.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  12.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  20.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  30.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  42.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  56.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  72.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  90.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 110.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 132.]]
[[  6.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.  12.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  20.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  30.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  42.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  56.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  72.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  90.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 110

True

In [30]:
H5 = ParticleOperator('a0 a0^ a0 a0')
print(np.matrix(displayMatrix(initializeMatrix(), H5)))
print(np.matrix(displayMatrixOld(initializeMatrix(), -2, -1, -1, -1, 0)))

[[ 0.          0.          4.89897949  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.         10.39230485  0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         17.88854382  0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.         27.38612788
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
  38.88444419  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.         52.38320341  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.         67.88225099  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.         85.38149682]
 [ 0.          0.          0.          0.          0.   

In [31]:
H6 = ParticleOperator('a0 a0^ a0 a0^')
print(np.matrix(displayMatrix(initializeMatrix(), H6)))
print(np.matrix(displayMatrixOld(initializeMatrix(), 0, 1, 1, 1, 1)))

[[  4.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   9.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  16.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  25.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  36.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  49.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  64.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  81.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 100.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 121.]]
[[  4.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   9.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  16.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  25.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  36.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  49.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  64.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  81.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 100

In [32]:
H7 = ParticleOperator('a0 a0^ a0^ a0')
print(H7)
Bra1 = Fock([], [], [(0, 1)]).dagger()
print(Bra1)
Ket1 = Fock([], [], [(0, 1)])
# print(Bra1 * H7 * Ket1)
print(np.matrix(displayMatrix(initializeMatrix(), H7)))

1.0*a_0a^†_0a^†_0a_0
1.0 * ⟨; ; (0, 1)|
[[  2.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   6.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  12.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  20.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  30.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  42.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  56.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  72.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  90.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 110.]]


In [33]:
# H7

print(np.matrix(displayMatrixOld(initializeMatrix(), 0, 0, 0, 1, 1)))

[[  2.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   6.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  12.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  20.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  30.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  42.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  56.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  72.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  90.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 110.]]


In [34]:
H8 = ParticleOperator('a0 a0^ a0^ a0^')
print(np.matrix(displayMatrix(initializeMatrix(), H8)))

print(np.matrix(displayMatrixOld(initializeMatrix(), 2, 3, 3, 1, 2)))

[[  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  9.79795897   0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.          17.32050808   0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.          26.83281573   0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.          38.34057903   0.
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.          51.84592559
    0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
   67.34983296   0.           0.           0

In [35]:
H9 = ParticleOperator('a0^ a0 a0 a0')
print(np.matrix(displayMatrix(initializeMatrix(), H9)))

print(np.matrix(displayMatrixOld(initializeMatrix(), -2, -2, -2, 0, -1)))

[[ 0.          0.          2.44948974  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          6.92820323  0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         13.41640786  0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.         21.9089023
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
  32.40370349  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.         44.89988864  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.         59.39696962  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.         75.89466384]
 [ 0.          0.          0.          0.          0.    

In [36]:
H10 = ParticleOperator('a0^ a0 a0 a0^')
print(np.matrix(displayMatrix(initializeMatrix(), H10)))

print(np.matrix(displayMatrixOld(initializeMatrix(), 0, 0, 0, 1, 1)))

[[  2.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   6.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  12.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  20.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  30.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  42.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  56.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  72.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  90.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 110.]]
[[  2.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   6.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  12.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  20.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  30.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  42.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  56.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  72.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  90

In [37]:
H11 = ParticleOperator('a0^ a0 a0^ a0')
print(np.matrix(displayMatrix(initializeMatrix(), H11)))

print(np.matrix(displayMatrixOld(initializeMatrix(), 0, 0, 0, 0, 0)))

[[  1.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   4.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   9.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  16.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  25.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  36.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  49.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  64.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  81.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 100.]]
[[  1.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   4.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   9.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.  16.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  25.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  36.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  49.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.  64.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.  81

In [38]:
H12 = ParticleOperator('a0^ a0 a0^ a0^')
print(np.matrix(displayMatrix(initializeMatrix(), H12)))

print(np.matrix(displayMatrixOld(initializeMatrix(), 2, 2, 2, 2, 1)))

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 7.34846923  0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.         13.85640646  0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.         22.36067977  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.         32.86335345  0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         45.36518489  0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.         59.86651819
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.   

In [39]:
H13 = ParticleOperator('a0^ a0^ a0 a0')
print(Fock([], [], [(0, 1)]).dagger() * H13)
print(np.matrix(displayMatrix(initializeMatrix(), H13)))

print(np.matrix(displayMatrixOld(initializeMatrix(), 0, 0, 0, -1, -1)))

0
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 12.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 20.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 30.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 42.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 56.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 72.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 90.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 12.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 20.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 30.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 42.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 56.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. 72.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. 90.]]


In [40]:
H14 = ParticleOperator('a0^ a0^ a0 a0^')
print(np.matrix(displayMatrix(initializeMatrix(), H14)))

print(np.matrix(displayMatrixOld(initializeMatrix(), 2, 1, 1, 1, 2)))

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 4.89897949  0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.         10.39230485  0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.         17.88854382  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.         27.38612788  0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         38.88444419  0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.         52.38320341
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.   

In [41]:
H15 = ParticleOperator('a0^ a0^ a0^ a0')
print(np.matrix(displayMatrix(initializeMatrix(), H15)))

print(np.matrix(displayMatrixOld(initializeMatrix(), 2, 0, 0, 1, 2)))

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 2.44948974  0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          6.92820323  0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.         13.41640786  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.         21.9089023   0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         32.40370349  0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.         44.89988864
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.   

In [42]:
H16 = ParticleOperator('a0^ a0^ a0^ a0^')
(1, 1)
print(np.matrix(displayMatrix(initializeMatrix(), H16)))

print(np.matrix(displayMatrixOld(initializeMatrix(), 4, 1, 2, 3, 4)))

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [10.95445115  0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.         18.97366596  0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.         28.98275349  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.         40.98780306  0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         54.99090834  0

In [43]:
opSum = ParticleOperator('a0^ a0^ a0^ a0^') + ParticleOperator('a0 a0 a0 a0') + ParticleOperator('a0^ a0^ a0^ a0^') + ParticleOperator('a0^ a0^ a0^ a0')+ ParticleOperator('a0 a0 a0 a0') 
# print(opSum)
# print(opSum.coeff)
# for op in opSum.HashMap:
#     print("coeff: ", opSum.HashMap[op])
#     print("op: ", op)

TypeError: __add__() missing 1 required positional argument: 'other2'